# -*- coding: utf-8 -*-
"""StreamBranchingInBeam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sqd02YNBcpu3yYd9iGZkJvV1Xr1ODKGn
"""

!ls
from google.colab import files
uploaded = files.upload()

! pip install apache-beam
import apache_beam as beam

#! {('mkdir data')}
p = beam.Pipeline()

input_collection = (
    p
    | "Read from file " >> beam.io.ReadFromText('dept_data.txt')
    | "Split Rows" >> beam.Map(lambda line : (line.split(",")))
)

account_count = (
    input_collection 
    | "Get all accounts dept person" >> beam.Filter(lambda record : record[3] == "Accounts")
    | "pair each employee with 1 " >> beam.Map(lambda l : (l[1],1))
    | "Group and Sum" >> beam.CombinePerKey(sum)
    | "Write results for account" >> beam.io.WriteToText('data/Accounts')
)

hr_count = (
    input_collection 
    |  beam.Filter(lambda record : record[3] == "HR")
    |  beam.Map(lambda l : (l[1],1))
    |  beam.CombinePerKey(sum)
    |  beam.io.WriteToText('data/HR')
)

output = (
    (account_count,hr_count)
    |"Combine two PCollections" >> beam.Flatten()
    | "Write as Parquet File" >> beam.io.WriteToText('data/both')
)

p.run()

! head -n 20 data/Accounts*
! head -n 20 data/HR*

! head -n 10 data/both*