# -*- coding: utf-8 -*-
"""StartingWithApacheBeam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_I8soi-lyn3cvAtdVOPdN0YkE9_nUBai
"""

from google.colab import files
uploaded = files.upload()

! pip install apache-beam
import apache_beam as beam

#! {(mkdir data)}
p1 = beam.Pipeline()

def SplitRow(element):
  return element.split(',')

def filtering(record):
  return record[3] == "Accounts"
attendance_count = (
    p1
    |"Read from data" >> beam.io.ReadFromText('dept_data.txt')
    | "Split data" >> beam.Map(lambda line : (line.split(",")))
    | "Filter" >> beam.Filter(filtering)
    | "Adding Key and value" >> beam.Map(lambda  l : (l[1],1))
    | "Combine by key" >> beam.CombinePerKey(sum)
    | "Write_File" >> beam.io.WriteToText('data/sample_data12121')
)

p1.run()

!head -n 20 data/*



























